### ISSUE TITLE
E_ERROR stcr_utils.php

### ISSUE THREAD

**Issue by wassereimer86** [stcr/subscribe-to-comments-reloaded#606]
This error happens when i want to edit an post from the Frontpage clicking the Button in the admin Bar. WordPress than sends a Mail with the following information (new since 5.5).

URL when error occured: ###/wp-admin/post.php?post=###&action=delete&_wpnonce=###

WordPress-Version 5.5
Aktuelles Plugin: Subscribe to Comments Reloaded (Version 200629)
PHP-Version 7.4.8

Fehler-Details
==============
Ein Fehler vom Typ E_ERROR wurde in der Zeile 316 der Datei ###/wp-content/plugins/subscribe-to-comments-reloaded/utils/stcr_utils.php verursacht. Fehlermeldung: Uncaught Error: Object of class WP_Post could not be converted to string in ###/wp-content/plugins/subscribe-to-comments-reloaded/utils/stcr_utils.php:316
Stack trace:
#0 ###/wp-content/plugins/subscribe-to-comments-reloaded/utils/stcr_utils.php(316): preg_replace()
#1 ###/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php(1089): stcr\stcr_utils->clean_email()
#2 ###/wp-includes/class-wp-hook.php(287): stcr\wp_subscribe_reloaded->delete_subscriptions()
#3 ###/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#4 ###/wp-includes/plugin.php(478): WP_Hook->do_action()
#5 ###/wp-includes/post.php(3078): do_action()
#6 ###/wp-includes/revision.php(456): wp_delete_post()
#7 ###

**Comment by BobaWebDev** [comment]
Hi @wassereimer86 

Thanks for the report, a change in the `delete_post` hook in WordPress 5.5 is what caused the issue, our plugin expected 1 parameter to be passed with it but in 5.5 another one was added (the WP Post object) and caused a problem.

Working on an update, will release in the next hour.

**Comment by BobaWebDev** [comment]
Hi @wassereimer86 

Just released the update. Give it a try, if you notice any issues please do let us know.

**Comment by wassereimer86** [comment]
Thank you for the quick fix! I don´t get this error anymore. 🙂

**Comment by BobaWebDev** [comment]
You're welcome :)
