### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to undefined function stcr\is_user_logged_in()

### ISSUE THREAD

**Issue by dave-weil-strategic** [stcr/subscribe-to-comments-reloaded#784]
Hi, 
We have been using the plugin(subscribe-to-comments-reloaded) on our website www.couplesinstitute.com for a long time but now it is causing some issues on the site. For more details, you can see the below log.

PHP message: PHP Fatal error: Uncaught Error: Call to undefined function stcr\is_user_logged_in() in /www/ci2022_697/public/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php:778
Stack trace:
#0 /www/ci2022_697/public/wp-includes/class-wp-hook.php(310): stcr\wp_subscribe_reloaded->subscribe_reloaded_manage(Array, Object(WP_Query))
#1 /www/ci2022_697/public/wp-includes/plugin.php(256): WP_Hook->apply_filters(Array, Array)
#2 /www/ci2022_697/public/wp-includes/class-wp-query.php(3511): apply_filters_ref_array('the_posts', Array)
#3 /www/ci2022_697/public/wp-includes/class-wp-query.php(3800): WP_Query->get_posts()
#4 /www/ci2022_697/public/wp-includes/post.php(2443): WP_Query->query(Array)
#5 /www/ci2022_697/public/wp-content/plugins/advanced-custom-fields-pro/includes/class-acf-internal-post-type.php(401): get_posts(Array)
#6 /www/ci2022_697/public/wp-content/plugins/advanced-custom-fields-pro/includes/class-acf-internal-post-type.php(359): ACF_Internal_Post_Type->get_raw_p" while reading response header from upstream, client: 47.128.29.50, server: www.couplesinstitute.com, request: "GET /comment-subscriptions/?sra=s&srk=40b02d88a33ceb50216b1e63bc030f74&srp=13190&srsrc=f HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.1-fpm-ci2022.sock:", host: "www.couplesinstitute.com:19421"

Please help us to resolve this issue as soon as possible.

Thanks

**Comment by BobaWebDev** [comment]
Hi @dave-weil-strategic 

Does it show everywhere or is it on some specific page or after a specific action?

**Comment by dave-weil-strategic** [comment]
Hi,

The source of these errors remains elusive, preventing us from pinpointing
the exact actions triggering them, and regrettably, we are unable to
replicate the issues for further analysis. Nevertheless, these errors
persistently manifest on the site at a frequent rate(every minute), with
detailed insights accessible through examination of our hosting server logs.

Thanks
