### ISSUE TITLE
PHP Fatal Error results in zero emails sent

### ISSUE THREAD

**Issue by TonyScialdone** [stcr/subscribe-to-comments-reloaded#801]
1. Leaving a comment works... but after the comment is stored, a fatal error occurs.
2. Replying to a comment works... but after, a fatal error occurs.
3. No emails have been sent by STCR in 30 days. I use AWS SES for SMTP, and they say things are fine on their end.
4. I use Easy WP SMTP for the connection, and they say things are fine on their end, that the error is in STCR.
 
Not sure how to troubleshoot. Thanks for your help!
Here's an example of the fatal error:

[22-May-2024 02:48:57 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "my_phpmailer_example" not found or invalid function name in /home/godwords/public_html/wp-includes/class-wp-hook.php:324
Stack trace:
#0 /home/godwords/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#1 /home/godwords/public_html/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#2 /home/godwords/public_html/wp-includes/pluggable.php(540): do_action_ref_array('phpmailer_init', Array)
#3 /home/godwords/public_html/wp-content/plugins/subscribe-to-comments-reloaded/utils/stcr_utils.php(520): wp_mail(Array, 'There is a new ...', '<html><head><ti...', Array)
#4 /home/godwords/public_html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php(1530): stcr\stcr_utils->send_email(Array)
#5 /home/godwords/public_html/wp-content/plugins/subscribe-to-comments-reloaded/wp_subscribe_reloaded.php(510): stcr\wp_subscribe_reloaded->notify_user('7987', 'elton@eltoncrow...', 46675)
#6 /home/godwords/public_html/wp-includes/class-wp-hook.php(326): stcr\wp_subscribe_reloaded->new_comment_posted(46675, 1)
#7 /home/godwords/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#8 /home/godwords/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /home/godwords/public_html/wp-includes/comment.php(2320): do_action('comment_post', 46675, 1, Array)
#10 /home/godwords/public_html/wp-includes/comment.php(3671): wp_new_comment(Array, true)
#11 /home/godwords/public_html/wp-comments-post.php(25): wp_handle_comment_submission(Array)
#12 {main}
  thrown in /home/godwords/public_html/wp-includes/class-wp-hook.php on line 324
[22-May-2024 07:53:50 UTC] PHP Warning:  Attempt to read property "post_type" on null in /home/godwords/public_html/wp-includes/link-template.php on line 4155
[22-May-2024 07:53:50 UTC] PHP Warning:  Attempt to read property "post_type" on null in /home/godwords/public_html/wp-includes/link-template.php on line 4157
[22-May-2024 12:59:34 UTC] PHP Warning:  Attempt to read property "post_type" on null in /home/godwords/public_html/wp-includes/link-template.php on line 4155
[22-May-2024 12:59:34 UTC] PHP Warning:  Attempt to read property "post_type" on null in /home/godwords/public_html/wp-includes/link-template.php on line 4157

**Comment by TonyScialdone** [comment]
Anybody home?
